### ISSUE TITLE
Issue: Already deployed my project.

### ISSUE THREAD

**Issue by Arslan49sp** [Arslan49sp/PortfolioMicro#12]
I am just creating this issue because i already deployed this code. following is the link. 
[https://arslan49sp.github.io/PortfolioMicro/](https://arslan49sp.github.io/PortfolioMicro/)

### Extra Note: 
This project is already approved by Microverse Reviewers. I am just submitting this review because i am repeating this module.

**Comment by divinecharlotte** [comment]
# Hello @Arslan49sp     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive issue👍 
- All sections on the page are  👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
